### ISSUE TITLE
barplot boxplot

### ISSUE THREAD

**Issue by lurebgi** [GuangchuangYu/plotTree-ggtree#1]
Hi, 

In the wechat page I saw a plot combined with a stacked barplot and barplot, but I don't see it here. Could you please also share the script for that as well? 

Thanks a lot,
Luohao
![571492775066_](https://cloud.githubusercontent.com/assets/5127153/25276093/c2c7f474-2698-11e7-9a21-8fbdec070c5f.jpg)

**Comment by GuangchuangYu** [comment]
see <https://guangchuangyu.github.io/2016/10/facet_plot-a-general-solution-to-associate-data-with-phylogenetic-tree/>.
